feat(products/search): add storefront search route / mock-functionality
labd/commercetools-node-mock pull request #209
Opened 2024-08-26 09:44 UTC by borisvankatwijk

## Changes

Addition of "products/search" POST endpoint. Also known as "Storefront Search -> Product Search".
https://docs.commercetools.com/api/projects/product-search#representations

## Search functionality partially supported

Since the purpose of this is to mock a product search result, we have not added facet, wildcard and boosting behaviour.
We feel this would be creating a "search replacement" for CommerceTools, instead of providing a mock to unit test searching product (format).

2024-08-26 11:11 UTC, demeyerthom requested changes

2024-08-26 11:11 UTC, demeyerthom commented on src/product-search.ts
> +			try {
Can you entirely remove the product filtering? We just want to returned whatever is in memory. Only implement pagination etc)

2024-08-27 07:53 UTC, borisvankatwijk commented on src/product-search.ts
> +			try {
Hi @demeyerthom ,

I have made the adjustments. No product filtering is applied now, to avoid unpredictable behaviour.

The "query" (_SearchQuery) is type validated in the mock (against @commerce-tools/sdk types).

2024-08-28 06:42 UTC, demeyerthom approved these changes
LGTM

2024-08-28 07:14 UTC, merged