chore: add set custom field to customer
labd/commercetools-node-mock pull request #84
Opened 2023-07-28 06:47 UTC by teddyteh

2023-07-28 09:48 UTC, okkevandereijk approved these changes

2023-07-29 11:49 UTC, mvantellingen commented on src/repositories/customer.ts
> +      if (!resource.custom) {
If the resource has no custom type defined it should throw an error, see the other resources as example

2023-07-29 11:49 UTC, mvantellingen requested changes
See comment

2023-07-31 02:19 UTC, teddyteh commented on src/repositories/customer.ts
> +      if (!resource.custom) {
Fixed, please check if the error message is acceptable.

2023-07-31 08:19 UTC, BramKaashoek approved these changes

2023-08-01 08:17 UTC, merged